In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv1D,MaxPool1D

from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.metrics import classification_report
from joblib import dump, load
import queue
import pandas as pd
import numpy as np
import glob, os, sys
pd.options.mode.chained_assignment = None



c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [34]:
with open('./Dataset/csv/Attack_merge.csv', newline='') as csvfile:
        rows = pd.read_csv(csvfile,header=None)
        y = rows[10]
        x = rows.drop([10], axis=1)
        X_train, X_test, y_train, y_test = train_test_split(x, y , test_size=0.2)
    
if not os.path.exists("./models"):
    os.mkdir("./models")

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/DT.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

0.970735524256651
              precision    recall  f1-score   support

           0       0.97      0.98      0.97     22798
           1       0.98      0.96      0.97     21932

    accuracy                           0.97     44730
   macro avg       0.97      0.97      0.97     44730
weighted avg       0.97      0.97      0.97     44730



In [3]:
model = RandomForestClassifier(n_estimators=20, max_depth=4)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/RF.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

0.948647440196736
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     22799
           1       0.99      0.91      0.95     21931

    accuracy                           0.95     44730
   macro avg       0.95      0.95      0.95     44730
weighted avg       0.95      0.95      0.95     44730



In [4]:
model = LogisticRegression(C=3)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/LR.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

0.9075788061703555
              precision    recall  f1-score   support

           0       0.91      0.91      0.91     22799
           1       0.90      0.91      0.91     21931

    accuracy                           0.91     44730
   macro avg       0.91      0.91      0.91     44730
weighted avg       0.91      0.91      0.91     44730



In [5]:
model = XGBClassifier(booster="gbtree", min_split_loss=7.100747859845302e-07, alpha=0.0010277375135306342, 
                        max_depth=9, eta=0.6737504946980999, gamma=6.101266632438708e-07, grow_policy="lossguide")
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/XGB.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[20:04:10] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0.9765034652358596
              precision    recall  f1-score   support

           0       0.98      0.97      0.98     22799
           1       0.97      0.98      0.98     21931

    accuracy                           0.98     44730
   macro avg       0.98      0.98      0.98     44730
weighted avg       0.98      0.98      0.98     44730



c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


In [6]:
model = LinearSVC(C = 2, verbose=False)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/SVM.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

0.9097250167672702
              precision    recall  f1-score   support

           0       0.91      0.91      0.91     22799
           1       0.91      0.91      0.91     21931

    accuracy                           0.91     44730
   macro avg       0.91      0.91      0.91     44730
weighted avg       0.91      0.91      0.91     44730



c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [7]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))
dump(model, './models/KNN.joblib')
prediction = model.predict(X_test)
print(classification_report(y_test,prediction))

0.9751844399731724
              precision    recall  f1-score   support

           0       0.98      0.97      0.98     22799
           1       0.97      0.98      0.97     21931

    accuracy                           0.98     44730
   macro avg       0.98      0.98      0.98     44730
weighted avg       0.98      0.98      0.98     44730



In [8]:
batch_size = 32
X_train = np.array(X_train)
y_train = np.array(y_train)

earlyStopping = EarlyStopping(monitor='val_loss', patience=3, verbose=0, mode='min')
mcp_save = ModelCheckpoint('./models/DNN4_Best_Model.h5', save_weights_only=False, save_best_only=True, monitor='val_loss', mode='min')
reduce_lr_loss = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=2, verbose=1, epsilon=1e-4, mode='min')

dnn4 = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=(X_train.shape[1],)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.01),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.01),
    tf.keras.layers.Dense(4, activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.01),
    tf.keras.layers.Dense(2, activation='softmax')
])

dnn4.compile(optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']);

dnn4.fit(X_train, y_train, batch_size=batch_size, epochs=10, verbose=1, callbacks=[earlyStopping, mcp_save, reduce_lr_loss], validation_split=0.25)
model = tf.keras.models.load_model('./models/DNN4_Best_Model.h5')

Epoch 1/10
4194/4194 [==============================] - 30s 7ms/step - loss: 0.2397 - accuracy: 0.8847 - val_loss: 0.1943 - val_accuracy: 0.8980
Epoch 2/10
4194/4194 [==============================] - 27s 6ms/step - loss: 0.1881 - accuracy: 0.9141 - val_loss: 0.2107 - val_accuracy: 0.8960
Epoch 3/10
4194/4194 [==============================] - 29s 7ms/step - loss: 0.1814 - accuracy: 0.9173 - val_loss: 0.1757 - val_accuracy: 0.9221
Epoch 4/10
4194/4194 [==============================] - 29s 7ms/step - loss: 0.2010 - accuracy: 0.9113 - val_loss: 0.1880 - val_accuracy: 0.8985
Epoch 5/10
4194/4194 [==============================] - 29s 7ms/step - loss: 0.1934 - accuracy: 0.9125 - val_loss: 0.1772 - val_accuracy: 0.9241

Epoch 00005: ReduceLROnPlateau reducing learning rate to 0.00010000000474974513.
Epoch 6/10
4194/4194 [==============================] - 28s 7ms/step - loss: 0.1846 - accuracy: 0.9168 - val_loss: 0.1591 - val_accuracy: 0.9275
Epoch 7/10
4194/4194 [==========================

In [9]:
preds = model.predict(X_test)
pred_labels = np.rint(preds)
accuracy = sklearn.metrics.accuracy_score(y_test, pred_labels[0:,1])
f1 = sklearn.metrics.f1_score(y_test, pred_labels[0:,1], average="binary")
prec = sklearn.metrics.precision_score(y_test, pred_labels[0:,1], average="binary")
recall = sklearn.metrics.recall_score(y_test, pred_labels[0:,1], average="binary")
print("accuracy: " + str(accuracy))
print("f1: " + str(f1))
print("prec: " + str(prec))
print("recall: " + str(recall))

accuracy: 0.9312541918175721
f1: 0.9284767287697998
prec: 0.94763080429209
recall: 0.9100816196251881


In [10]:
model = tf.keras.models.load_model('./models/DNN4_Best_Model.h5')

In [37]:
X_train_np = np.array(X_train).reshape(X_train.shape[0], X_train.shape[1], 1)
print(X_train_np.shape)
y_train_np = np.array(y_train).reshape(y_train.shape[0], 1)
print(y_train_np.shape)

(178919, 10, 1)
(178919, 1)


In [39]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Conv1D, MaxPooling1D, Embedding, GlobalAveragePooling1D
epochs = 10
batch_size = 32

model = Sequential()
model.add(Conv1D(filters=100, kernel_size=10, activation='relu',strides=5, input_shape=(X_train.shape[0],X_train.shape[1])))
model.add(MaxPooling1D(2))
model.add(Conv1D(filters=200, kernel_size=10, activation='relu',strides=5))
model.add(MaxPooling1D(2))
model.add(Conv1D(filters=400, kernel_size=10, activation='relu',strides=5))
model.add(GlobalAveragePooling1D())
model.add(Dropout(0.4))
model.add(Dense(2, activation='softmax'))
model.compile(loss='mean_absolute_error', optimizer= 'adam')
model.summary()

model.fit(X_train_np, y_train, epochs=epochs, batch_size=batch_size,) 

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_31 (Conv1D)           (None, 35782, 100)        10100     
_________________________________________________________________
max_pooling1d_20 (MaxPooling (None, 17891, 100)        0         
_________________________________________________________________
conv1d_32 (Conv1D)           (None, 3577, 200)         200200    
_________________________________________________________________
max_pooling1d_21 (MaxPooling (None, 1788, 200)         0         
_________________________________________________________________
conv1d_33 (Conv1D)           (None, 356, 400)          800400    
_________________________________________________________________
global_average_pooling1d_10  (None, 400)               0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 400)             

ValueError: in user code:

    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\training.py:795 train_step
        y_pred = self(x, training=True)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    c:\Users\Maxwang\anaconda3\envs\Adversarial_attack_\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:251 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_12 is incompatible with the layer: expected axis -1 of input shape to have value 10 but received input with shape (None, 10, 1)


In [41]:
print(X_train_np.reshape(-1,10,1))

[[[5.1759650e-03]
  [0.0000000e+00]
  [0.0000000e+00]
  ...
  [0.0000000e+00]
  [0.0000000e+00]
  [0.0000000e+00]]

 [[3.1000000e-06]
  [3.3000000e+02]
  [0.0000000e+00]
  ...
  [0.0000000e+00]
  [0.0000000e+00]
  [0.0000000e+00]]

 [[6.9900000e-05]
  [5.0100000e+02]
  [0.0000000e+00]
  ...
  [0.0000000e+00]
  [0.0000000e+00]
  [0.0000000e+00]]

 ...

 [[1.3695955e-02]
  [5.0100000e+02]
  [0.0000000e+00]
  ...
  [0.0000000e+00]
  [0.0000000e+00]
  [0.0000000e+00]]

 [[5.1690510e-03]
  [3.3000000e+02]
  [1.3000000e+01]
  ...
  [1.3000000e+01]
  [1.7100000e+02]
  [0.0000000e+00]]

 [[5.1818790e-03]
  [3.3000000e+02]
  [1.3000000e+01]
  ...
  [1.3000000e+01]
  [1.7100000e+02]
  [0.0000000e+00]]]


In [42]:
X_train_np.shape

(178919, 10, 1)